settings:
  base_save_dir: "./output/activations"
  base_classify_dir: "./output/classifications"
  batch_size: 10
  model_type: "llm"
  sae_location: "res"
  test_size: 0.4
  tree_depth: 5
  act_only: True
  cuda_visible_devices: "0,1,2"
  bow_baseline: "True"

models:
  - name: "google/gemma-2b"
    layers: [6, 12, 17]
    widths: ["16k"]

  - name: "google/gemma-2-2b"
    layers: [5, 12, 19]
    widths: ["16k", "65k"]

  - name: "google/gemma-2-9b"
    layers: [9, 20, 31]
    widths: ["16k"]

  - name: "google/gemma-2-9b-it"
    layers: [9, 20, 31]
    widths: ["16k"]

datasets:
  - name: "Anthropic/election_questions"
    config_name: ""
    split: "test"
    text_field: "question"
    label_field: "label"


classification_params:
  top_n_values: [0, 20, 50]
  binarize_values: [null, 1.0]
  extra_top_n: -1
  extra_binarize_value: null
