settings:
  base_save_dir: "./output/activations"
  base_classify_dir: "./output/classifications"
  batch_size: 64
  model_type: "llm"
  sae_location: "res"
  test_size: 0.2
  tree_depth: 5
  act_only: True
  cuda_visible_devices: "0,1,2"
  bow_baseline: "True"

models:
  - name: "google/gemma-2-2b"
    layers: [5, 12, 19]
    widths: ["1m"]

  - name: "google/gemma-2-9b"
    layers: [9, 20, 31]
    widths: ["131k", "1m"]

  - name: "google/gemma-2-9b-it"
    layers: [9, 20, 31]
    widths: ["131k"]

datasets:
  - name: "Anthropic/election_questions"
    config_name: ""
    split: "test"
    text_field: "question"
    label_field: "label"

  - name: "willcb/massive-scenario"
    config_name: ""
    split: "train"
    text_field: "input"
    label_field: "label" 

  - name: "willcb/massive-intent"
    config_name: ""
    split: "train"
    text_field: "input"
    label_field: "label" 

  - name: "legacy-datasets/banking77"
    config_name: ""
    split: "train"
    text_field: "text"
    label_field: "label"  
  
  - name: "AIM-Harvard/multilingual_toxicity_dataset"
    config_name: ""
    split: "es"
    text_field: "text"
    label_field: "toxic"

  - name: "AIM-Harvard/multilingual_toxicity_dataset"
    config_name: ""
    split: "de"
    text_field: "text"
    label_field: "toxic"

  - name: "AIM-Harvard/multilingual_toxicity_dataset"
    config_name: ""
    split: "ru"
    text_field: "text"
    label_field: "toxic"
  
  - name: "AIM-Harvard/multilingual_toxicity_dataset"
    config_name: ""
    split: "zh"
    text_field: "text"
    label_field: "toxic"
  
  - name: "AIM-Harvard/multilingual_toxicity_dataset"
    config_name: ""
    split: "en"
    text_field: "text"
    label_field: "toxic"

  - name: "textdetox/multilingual_toxicity_dataset"
    config_name: ""
    split: "es"
    text_field: "text"
    label_field: "toxic"

  - name: "textdetox/multilingual_toxicity_dataset"
    config_name: ""
    split: "de"
    text_field: "text"
    label_field: "toxic"

  - name: "textdetox/multilingual_toxicity_dataset"
    config_name: ""
    split: "ru"
    text_field: "text"
    label_field: "toxic"
  
  - name: "textdetox/multilingual_toxicity_dataset"
    config_name: ""
    split: "zh"
    text_field: "text"
    label_field: "toxic"
  
  - name: "textdetox/multilingual_toxicity_dataset"
    config_name: ""
    split: "en"
    text_field: "text"
    label_field: "toxic"
  
  - name: "SetFit/tweet_eval_stance_abortion"
    config_name: ""
    split: "train"
    text_field: "text"
    label_field: "label_text"

  - name: "AIM-Harvard/reject_prompts"
    config_name: ""
    split: "train"
    text_field: "text"
    label_field: "label"

  - name: "jackhhao/jailbreak-classification"
    config_name: ""
    split: "test"
    text_field: "prompt"
    label_field: "type"
    
  - name: "cardiffnlp/tweet_sentiment_multilingual"
    config_name: "english"
    split: "test"
    text_field: "text"
    label_field: "label"

  - name: "cardiffnlp/tweet_sentiment_multilingual"
    config_name: "spanish"
    split: "test"
    text_field: "text"
    label_field: "label"

  - name: "cardiffnlp/tweet_sentiment_multilingual"
    config_name: "french"
    split: "test"
    text_field: "text"
    label_field: "label"

  - name: "cardiffnlp/tweet_sentiment_multilingual"
    config_name: "german"
    split: "test"
    text_field: "text"
    label_field: "label"

  - name: "cardiffnlp/tweet_sentiment_multilingual"
    config_name: "portuguese"
    split: "test"
    text_field: "text"
    label_field: "label"

  - name: "cardiffnlp/tweet_sentiment_multilingual"
    config_name: "italian"
    split: "test"
    text_field: "text"
    label_field: "label"

  - name: "cardiffnlp/tweet_sentiment_multilingual"
    config_name: "arabic"
    split: "test"
    text_field: "text"
    label_field: "label"

  - name: "cardiffnlp/tweet_sentiment_multilingual"
    config_name: "hindi"
    split: "test"
    text_field: "text"
    label_field: "label"

  # - name: "gallifantjack/pminervini_NQ_Swap_org_answer_None_openai_google_gemma_2_9b_it"
  #   config_name: ""
  #   split: "train"
  #   text_field: "user"
  #   label_field: "score"

  # - name: "gallifantjack/pminervini_NQ_Swap_org_answer_question_openai_google_gemma_2_9b_it"
  #   config_name: ""
  #   split: "train"
  #   text_field: "user"
  #   label_field: "score"

  # - name: "gallifantjack/pminervini_NQ_Swap_sub_answer_question_openai_google_gemma_2_9b_it"
  #   config_name: ""
  #   split: "train"
  #   text_field: "user"
  #   label_field: "score"

classification_params:
  top_n_values: [0, 20, 50]
  binarize_values: [null, 1.0]
  extra_top_n: -1
  extra_binarize_value: null
